# Generated by Django 4.1.13 on 2024-02-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
